### ISSUE TITLE
Opennms in DOCKER 

### ISSUE THREAD

**Issue by kamritk** [opennms-forge/docker-horizon-core-web#35]
Running opennms in Docker will create IO issue? if yes please let know how to overcome we have around 1 lakh interfaces among that 75k interfaces enabled for polling

**Comment by indigo423** [comment]
This is not related to Docker in my opinion. OpenNMS in general will create a lot of IO when you monitor a lot of devices and metrics. What do you think is necessary to solve this issue here?
