### ISSUE TITLE
 /opennms-data/logs - Not linked correctly 

### ISSUE THREAD

**Issue by syepes** [opennms-forge/docker-horizon-core-web#45]
Hello @indigo423 

I have just noticed that in the last Docker images the symbolic link of the logs to the volume opennms-data is no longer working.

Old Docker Image
```
ls -l /opt/opennms/ |egrep "logs|share"
lrwxrwxrwx.  1 root root    18 Oct  9 02:03 logs -> /opennms-data/logs
lrwxrwxrwx.  1 root root    12 Oct  9 02:03 share -> /var/opennms
```

Last Docker Image
```
ls -l /opt/opennms/ |egrep "logs|share"
lrwxrwxrwx  1 root root    16 Oct 19 21:15 logs -> /var/log/opennms
lrwxrwxrwx  1 root root    12 Oct 19 21:15 share -> /var/opennms
```

**Comment by indigo423** [comment]
@syepes does this issue still exist. I've checked it on my instance and works for me?

**Comment by syepes** [comment]
Yes this one is also resolved, must of been a one time bug.
