### ISSUE TITLE
Allow initial custom configuration on startup

### ISSUE THREAD

**Issue by indigo423** [opennms-forge/docker-horizon-core-web#5]
As a user, I would like to have a configuration directory which allows me to overwrite just specific configuration files on startup. For example, I have just changed the poller-configuration.xml, there should be a directory which gives me the possibility to overwrite just this file from the pristine config.

**Comment by soleger** [comment]
Do you mean, whatever files you put into the directory are imported directly over top of the files that exist in the container? Do you envision this primarily as a one-time option for initial configuration?

**Comment by indigo423** [comment]
@gallenc came up with this use case. There is one problem, you can only copy files into the container during build-time not runtime. Our configuration is not made for running in a container, so having them accessible persisted somewhere is the only solution I can think of right now. But happy for any input here.
