### ISSUE TITLE
The Monitor Class for new poller service is N/A and the service is always marked as running

### ISSUE THREAD

**Issue by namnhatdoan** [opennms-forge/docker-horizon-core-web#55]
I added a poller service named MySQL3307 to the poller-configuration.xml file and using the TCPMonitor for it then run the event reloadDaemonConfig for Pollerd service. But after that, in the Web UI, the Monitor Class is N/A, and this service is always marked as running.

I defined the MySQL3307 in the configuration file as below:
```
<service name="MySQL3307" interval="300000" user-defined="true" status="on">
         <parameter key="retry" value="1"/>
         <parameter key="timeout" value="3000"/>
         <parameter key="port" value="3307"/>
         <parameter key="banner" value="*"/>
      </service>
<monitor service="MySQL3307" class-name="org.opennms.netmgt.poller.monitors.TcpMonitor"/>
```
Here is a screenshot when I open the Web UI.
![image](https://user-images.githubusercontent.com/31526797/54339782-6239a980-4668-11e9-9a10-d039b071dc8a.png)

I also tried to modify some parameters and the class-name of the service MySQL (from the TCPMonitor to JDBCMonitor) and send the event reloadDaemonConfig. When I check on the Web UI, the parameter is updated but the Monitor Class of MySQL is still TCP.

How can I fix it? Or if there is any document or link related to this issue, please show me.

I installed OpenNMS using docker with the latest version currently. Just clone the repository and run the command docker-compose up -d.

Thank you

**Comment by indigo423** [comment]
Hello @namnhatdoan this topic is not related to the docker image itself and seems to be a problem with the application itself. Would you be so kind, moving it to our [Community Support](https://opennms.discourse.group/c/community-support) where the peoples live answering this type of questions?

**Comment by indigo423** [comment]
I'll close this issue, further discussions on this topic can be followed up in this topic [here](https://opennms.discourse.group/t/the-monitor-class-of-user-defined-poller-service-is-n-a-and-the-status-of-monitored-service-is-always-running/300?u=indigo)

**Comment by indigo423** [comment]
I'll close this issue, further discussions on this topic can be followed up in this topic [here](https://opennms.discourse.group/t/the-monitor-class-of-user-defined-poller-service-is-n-a-and-the-status-of-monitored-service-is-always-running/300?u=indigo).
