### ISSUE TITLE
docker-compose up - fails with opennms.hzn.core.web exited with code 2

### ISSUE THREAD

**Issue by nikkova** [opennms-forge/docker-horizon-core-web#9]
Here is the error I get:

_opennms.hzn.core.web | OpenNMS configuration already initialized.
opennms.hzn.core.web | sed: can't read /opt/opennms/etc/org.apache.karaf.shell.cfg: No such file or directory
opennms.hzn.core.web exited with code 2__

It cant find file org.apache.karaf.shell.cfg when I attempt to start image- what am I missing?

psql image starts with no issues..

**Comment by indigo423** [comment]
Can you please share your docker-compose.yml you have used?

**Comment by nikkova** [comment]
It's stock standard - no mods.. what ever I pulled from the repo.

**Comment by nikkova** [comment]
Attached..

**Comment by indigo423** [comment]
I've figured it out, it happens when you have the configuration for opennms (/opt/opennms/etc) in a local volume, see here in [L37](https://github.com/opennms-forge/docker-horizon-core-web/blob/master/docker-compose.yml#L37). For the reason you have to configure OpenNMS via editing config files, I've mounted it to my host system and maintain it with git. When you change the line to this it should work.

```
- ./etc:/opt/opennms/etc
```

I'll open an issue for this problem. It should work also with a local volume. Thanks for reporting.

**Comment by nikkova** [comment]
hmm.. no joy!

[root@ip-####### docker-horizon-core-web]# docker-compose up
Starting opennms.psql ...
Starting opennms.psql ... done
Starting opennms.hzn.core.web ...
Starting opennms.hzn.core.web ... done
Attaching to opennms.psql, opennms.hzn.core.web
opennms.psql | LOG:  could not create IPv6 socket: Address family not supported by protocol
opennms.psql | LOG:  database system was shut down at 2017-08-08 07:00:30 UTC
opennms.psql | LOG:  MultiXact member wraparound protections are now enabled
opennms.psql | LOG:  database system is ready to accept connections
opennms.psql | LOG:  autovacuum launcher started
opennms.hzn.core.web | OpenNMS configuration already initialized.
opennms.hzn.core.web | sed: can't read /opt/opennms/etc/org.apache.karaf.shell.cfg: No such file or directory
opennms.hzn.core.web exited with code 2

Updated line 37 as requested:
/--snip--/
    depends_on:
      - database
    volumes:
      - ./etc:/opt/opennms/etc
      - opennms.data:/opennms-data
      # - /data/opennms/etc:/opt/opennms/etc
      # - opennms.data:/opt/opennms/etc
    command: ["-s"]
/--snip/

**Comment by indigo423** [comment]
When you run the container it should have created a `etc` directory where your docker-compose.yml is. Can you delete it? It will be recreated from a pristine configuration inside the image.

**Comment by nikkova** [comment]
Had to manually create ./etc dir.  Not sure why it was not creating it. 
It's now working and  thanks heaps for your help!

**Comment by indigo423** [comment]
This is interesting, the directory is created when it does not exist automatically when I run `docker-compose up -d`. Which version of docker and docker-compose do you have?

Thanks for feedback and happy you got it running :)
